language: python

python:
  - "3.6"

env:
  - DELPHI_DATA=$TRAVIS_BUILD_DIR/data

addons:
  apt:
    packages:
    - graphviz

install:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  - pip install pipenv
  - pipenv install -d --skip-lock
  - mkdir data; cd data; wget http://vision.cs.arizona.edu/adarsh/delphi.db

script: make test
after_success: coveralls
cache: pip
